### ISSUE TITLE
Create data set to classify Pidgey

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#20]
According to the plots of the dummy and api data most of the sights in our data are from Pidgey. Therefore we want to modify the existing data set to classify if a sighting is from Pidgey or not.

You can use the dummy data for this classifier since it has about 600 entries whereas the apiData has about 2500. So if you want to save some time while building the classifier stick to the small data set ;)
1. Create an .arff which contains 
   - `timestamp, latitude, longitude` as attributes, all are numeric.
   - `isPidgey` as class label, which can either be _true_ or _false_. The class label will be _true_ if the data entry has the `pokemonId == 16` otherwise it is _false_.
2. Test if you can open the data set in Weka
3. upload the file (PR)
4. run Weka and see how the data set performs. try different approaches, as Tatyana mentioned in [the last two points of her comment](https://github.com/PokemonGoers/PredictPokemon-2/issues/9#issuecomment-244321609). The rest of us will also test the data set.

To create the .arff file just adapt one of the existing scripts we already have in the repo.

**Comment by goldbergtatyana** [comment]
hi there, the arff file will change many many times later. Now we need to concentrate on getting and incorporating as many features as possible into it. Then we will do feature selection (based on weka statistics we will throw some of the features out). Only afterwards it makes sense to train and test the model .. not at this moment now.

**Comment by MatthiasBaur** [comment]
We moved pass the binary classifiers.
