### ISSUE TITLE
Split getApi into Api-to-JSON and JSON-to-arff

### ISSUE THREAD

**Issue by MatthiasBaur** [PokemonGoers/PredictPokemon-2#22]
@bensLine
Since we are adding and removing features all the time it would be nice to have an easy entrypoint. Since we get the data in JSON format, we can just use it to add more features.

**Comment by bensLine** [comment]
Yes that's a good point, I have an idea how to set this up. I'll implement it later. Should be up in the afternoon

**Comment by MatthiasBaur** [comment]
This issue was addressed in https://github.com/PokemonGoers/PredictPokemon-2/tree/feature/featureSourceSetup
