### ISSUE TITLE
Possible corellation between ingress's XM and Pokemon appearance

### ISSUE THREAD

**Issue by semioniy** [PokemonGoers/PredictPokemon-2#3]
- Hypotesis: the more XM there is on some spot in ingress, the bigger is the likelyhood of pokemon appearance there
- Examine possible corellation between type/ level of rareness of a pokemon depending on specificity of the area in ingress

**Comment by goldbergtatyana** [comment]
good ideas, @semioniy. what would be the data sources?

**Comment by semioniy** [comment]
I was trying to find a map with these XM, but damn, there is no way to have one except for using the Ingress app itself.
Sure we could try to hack the app/ intercept the server respond to the app, but, I guess, it will be too time consuming and won't work for "official" service like we are trying to do. So, we could orient ourselves on ingress when searching for pokemons, but, probably, nothing more.
