### ISSUE TITLE
Upload data set into Kaggle

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PredictPokemon-2#35]
Please generate a Kaggle page for our PokemonGo prediction and turn it into a challenge. For the time being keep the challenge invite only. Please upload your datasets onto the kaggle page. 

Here is an example of a [Kaggle page that was inspired by our Game of Thrones](https://www.kaggle.com/mylesoneill/game-of-thrones) project and uses the datasets we generated. 
## And now to this semester's surprise challenge:

Once the page is set up there will be a group from Microsoft Bing's Core Relevance and Ranking that **will be invited to the challenge and try offer their own predictions.** 

We have all confidence that the TUM team will come on top! 🙏

**Comment by gyachdav** [comment]
Status?

**Comment by semioniy** [comment]
Status - still busy with weather)

**Comment by sacdallago** [comment]
For the sightings data: I am creating dump of the production DB which collected over the last 3 days (almost 6 gigs of data).

How is it on your end @semioniy ??

**Comment by semioniy** [comment]
@sacdallago we now have the 50k dataset with all current features.

**Comment by sacdallago** [comment]
Oh nice! :)

**Comment by semioniy** [comment]
Now the question is only, how Kaggle works, and how fast they answer me.

**Comment by semioniy** [comment]
BTW, @gyachdav @sacdallago, when kaggle answers me about making a challenge, should I promise some kind of prize? As I understood, that is the sense of Kaggle, finding a better method and winning a prize.

**Comment by gyachdav** [comment]
No prize. There are many challenges that are there for fame and glory.

**Comment by goldbergtatyana** [comment]
you'll update us on the news from kaggle, right @semioniy ? 😈

**Comment by semioniy** [comment]
Yeah, sure. But there' not much to say though.
They contacted me, asking what's the project about and what we want. I answered them and now wait for their reaction.
Bad thing, that we only contact each other via email, so the conversation is pretty slow.

**Comment by gyachdav** [comment]
Please email Kaggle again and ask for a status update. please put us (mentors) in cc. Thanks.

**Comment by semioniy** [comment]
@gyachdav we emailed today, so there is probably no status update yet. When they write me next time, I'll put you in cc.

**Comment by semioniy** [comment]
https://www.kaggle.com/semioniy/predictemall

**Comment by semioniy** [comment]
I uploaded and made it ready, maybe they just need some time.

**Comment by goldbergtatyana** [comment]
Thanks @semioniy. The kaggle page looks good and I especially like your description to the challenge. What I am missing though is the description of the data points and their features, i.e. what were the sources used to get the data and what are the possible values of our features?

**Comment by sacdallago** [comment]
Also please note that a new dataset should be uploaded, which is the one mined from our own team A @PokemonGoers/pokedata . Dataset is on its way trough something similar to UPS in the form of our magnificent @goldbergtatyana :laughing:

**Comment by goldbergtatyana** [comment]
Thanks @sacdallago for creating the file!

The json file with the copy of our MongoDB can now be downlaoded from https://rostlab.org/~goldberg/catchemall.json

@semioniy please make a new csv file with features for the data from this file and upload it on kaggle
@MatthiasBaur please go ahead and use this data to verify the prediction performance of the algorithm you found to provide best results

**Comment by goldbergtatyana** [comment]
The file is ~2G in size and contains ~9M entries. 

It can be downloaded to your linux machine directly using

``` bash
wget https://rostlab.org/~goldberg/catchemall.json
```

**Comment by semioniy** [comment]
Hey, @goldbergtatyana, @sacdallago, first you told me to upload a dataset with as many features as possible. But now it's eather all features, or 9M dataset.
If I upload a 9M dataset, it's only possible with less features, which basically makes it an other dataset, not a New Version.

P.S. *because I can't gather weather for 9Mil entries I mean, and with different features it's a different dataset.

**Comment by sacdallago** [comment]
@semioniy thanks for the update. Can you not upload this as an additional dataset, as is? Not necessary to calculate the features for these, for now -at least, not for the kaggle-.
You are totally correct: this should not replace the existing dataset, it is not meant as a _new version_, simply because most of these points are not verifiable and we actually have knowledge that some are purely statistical with no relevance (though we don't know which ones).

We can sample some of the points in this data and calculate features for those, in case. Internally. Additionally this data presents a `source` label, which might help figuring out which services are reliable and which ones are not. And I guess, that's what @MatthiasBaur is having fun with ATM.

**Comment by MatthiasBaur** [comment]
Lots of fun :)

**Comment by goldbergtatyana** [comment]
ok just to repeat, @semioniy please upload the new file as an additional file for sightings. Just please add descriptions for both files.

@MatthiasBaur we need to sample features for 10K randomly drawn datapoints from this file (preferably of the last day, thats what you did on the prev data set, right?), but only those features that you found to be useful for the reddit data set. Then we nee dto apply 10 fold cv to confirm the prediction performance of ~21% on this data set as well.

**Comment by goldbergtatyana** [comment]
btw, @MatthiasBaur and @semioniy since we cannot predict rare pokemons anyways (too little data and they seem not to follow appearance patterns of other pokemons) then we dont need to combine them in one class, why the extra work?

**Comment by goldbergtatyana** [comment]
@semioniy @semioniy please upload the new dataset to kaggle, including descriptions of the data sets. Let us know if you need help. Thank you!

**Comment by semioniy** [comment]
@goldbergtatyana sorry, had problems with internet in my dorms, now online again.
I can't download the dataset, can you upload it somewhere else? Dropbox would be perfect.

P.S do I understand right?: Now I'm responsible for Kaggle page. People keep asking questions there)

**Comment by goldbergtatyana** [comment]
That's cool @semioniy, here is the link https://www.dropbox.com/s/5js9vvsgerph0pi/catchemall.json?dl=0

**Comment by semioniy** [comment]
Hi, @goldbergtatyana, 
This file is not much of a use, cause neither webstorm, nor any text editor can handle it. 9Mil seems to be too much.
Maybe, if it were 9 files a million entries each, I could convert them, but still I doubt there would be a way to merge them together not using some server-guys-tricks (which I don't know).
As is, there is not much sense in uploading the file, I think, cause it's just coordinates, date and class, isn't it?

**Comment by goldbergtatyana** [comment]
Hey @semioniy , there is no need to open the file with a text editor as long as we provide descripton for the file and maybe the first ten lines of the file as a sample 😏 

Please go ahead and upload the whole file as is. The file will then be read programatically or with linux tools.

**Comment by sacdallago** [comment]
@semioniy 

a) If using win best new feature of windows 10: **LINUX**
1. https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

b) How to check out file contents
1. http://ss64.com/bash/more.html
2. http://ss64.com/bash/less.html
3. http://ss64.com/bash/tail.html

**Comment by goldbergtatyana** [comment]
Nice @sacdallago , thanks a lot for the hints 👏 

@MatthiasBaur can you confirm the same prediction performance of ~21% on randomly chosen 10K data points from the big set?

**Comment by sacdallago** [comment]
Ah, ah. Since this is a js seminar. You can do the following too:
1. Start `node` from within the folder with that file (let's suppose it's called `file.json`).
2. Once the node console is open, write `var t = require('file');`
3. Now you can do whatever you want wit those entries (it's an array, if I'm not mistaken). Eg, from the console:

``` javascript
> console.log(t[0]); // First element
> var last_element = t[t.length - 1]; // Last element
> console.log(last_element );
> for (var i = 0; i < 10; i++) { console.log(t[i]); } // First 10 elements
> var item = t[Math.floor(Math.random()*t.length)]; // Random element
```

if you write a js script that randomly draws x elements from the array (with or without substitution), you can even build your own 10K dataset.

No need to ever use a text editor :)

**Comment by semioniy** [comment]
@sacdallago thanx for advice about node. After minor changes (`'./file'` instead of `'file'`) it worked, but only with smaller files. Located in the same folder, `catchemall.json` doesn't even get imported after require. I get an error:
`Error: toString failed`
I assume it's because of the file size, but, maybe, the file is corrupted. Did you, or @goldbergtatyana try to open it yourself?
I'll try sublime now and write, how it went.

**Update**
It worked with sublime, now I'll upload the file. BTW yes, this could not be read as an array because `[` and `]` were missing.

**Comment by gyachdav** [comment]
@semioniy check the upload restrictions on Kaggle

**Comment by semioniy** [comment]
Aaand, this is what Kaggle says when uploading the file:

> The zip file 'catchemall.zip' contains a file 'catchemall.json' (1.94 GB) that exceeds the max size allowed of 500.00 MB.

**Comment by gyachdav** [comment]
yeah thought so... just split it up then to several 500MB files. 

on debian/ubuntu you can:

split --bytes=500M /path/to/catchemall.json

**Comment by sacdallago** [comment]
@gyachdav won't this deteriorate the data formatting? @semioniy you might need to look at the end and beginnings of files, making sure objects are closed and not truncated and that the array form is kept consistent, aka:

END OF FILE 1

``` javascript
...}, {"timestamp": "UT
```

BEGGINING OF FILE 2

``` javascript
C-xxx", "some attribute": "some value",..},...
```

TO

``` javascript
...}]
```

``` javascript
[{"timestamp": "UTC-xxx", "some attribute": "some value",..},...
```

**Comment by gyachdav** [comment]
Or you can just have in the readme instructions how to rebuild the files (using join). Either way works. let's get it done today.

**Comment by goldbergtatyana** [comment]
Yep, I was opening the file with http://ss64.com/bash/less.html and http://ss64.com/bash/more.html. It looked alrigh to me. Thanks @semioniy for uploading 👍

**Comment by MatthiasBaur** [comment]
I ran our classifier on 10k datapoints and got ~20 %. The small drop is probably due to an unequal distribution of the data across the day (The last 10k are spread across 5 hours). I will recheck this with a better distribution, however I cannot give you a deadline for this, because of an exam Wednesday morning.

Some other relevant command when working with this file:

```
// sort in descending order
//relevant after preprocessing (e.g. arranging date in first pos, extracting lat/lon)
sort -r file.txt
//get first 10000 entries
head -10000 file.txt >output.txt
```

And if you want to work with the files in js. Either use streaming ops or split the file.
`split -b 100M file.txt split_file.txt.`
And then `cat` them later.

**Comment by goldbergtatyana** [comment]
thats good news @MatthiasBaur , viel Erfolg on Wed!

**Comment by semioniy** [comment]
People are asking serious questions [here](https://www.kaggle.com/forums/f/1614/predict-em-all/t/24061/dataset-update-questions/138596#post138596) on Kaggle. Questions I have no answers to. Need help. @bensLine maybe you know why it is as it is?

P.S. Datadump has been uploaded.

**Comment by sacdallago** [comment]
@MatthiasBaur maybe also try leaving one of the data sources out? We don't know how much a data source is accurate.. So, do the 10K sampling, and then filter out by data source?

Just proposing :)

**Comment by sacdallago** [comment]
@goldbergtatyana we are getting noticed on kaggle :) Reddit all over again :D

**Comment by goldbergtatyana** [comment]
Oh wow, what an activity on kaggle: 1,856 views · 339 downloads · 5 kernels · 3 topics

@PokemonGoers/predictpokemon-2 how come there is no Monday as a possible instance for the feature _appearedDayOfWeek_, instead there is a day called"dummy_day" ?

**Comment by goldbergtatyana** [comment]
@semioniy I expanded the description of the dataset in https://docs.google.com/document/d/1dIKvxOshOCnu2by5gIQR3rceUAs_4cfhg3TDxS9bPnM/edit

Please have a look, replace the red text (this is the info I dont know/unsure about) and copy/paste the description to the kaggle page. Having the data documented as precisely as possible will help to avoid many questions upfront :)

@MatthiasBaur  @gyachdav @sacdallago please feel free to also review the file

**Comment by goldbergtatyana** [comment]
One of the questions from kaggle is very interesting, indeed, and I also cannot answer it. It goes: 

Hmm. I see that the 9th line in the arff file has pokemonid 35, but class is 19. Next line is just the other way around. And these are just the first of the discrepancies... ?

@PokemonGoers/predictpokemon-2 this should not be the case, of course! Can one of you guys check whats going on with lines 9 and 10 of the arff file?

**Comment by semioniy** [comment]
Ok, as nobody reacted on my comment, I'll repeat: someone [here](https://www.kaggle.com/forums/f/1614/predict-em-all/t/24061/dataset-update-questions/138596#post138596) asked a question, please check. It seems that our dataset has many mistakes. The questions are not about features, which are already described btw.

**Comment by semioniy** [comment]
@goldbergtatyana it's not only in these lines. This mistake repeats multiple times over the dataset.

**Comment by goldbergtatyana** [comment]
hopefully, the question of pokemon ids and class ids not matching in some lines of the arff file will be answered very soon, @semioniy 🙏

**Comment by bensLine** [comment]
I'll check it tomorrow. Concerning the dummy day, this is a unresolved bug

**Comment by bensLine** [comment]
I added a PR #65 for the Bug. However, I'm not yet sure if this was the only reason, but definitely one. If so, all poke ids should be wrong in the data set after the first wrong label. I'll check the kaggle file to hopefully confirm that :p

**Comment by goldbergtatyana** [comment]
Oh oh, what does this mean for the result of our predictions??

**Comment by bensLine** [comment]
Ok, seems like that was the problem. I looked over several entries in the data set and most have had this mismatch. sometimes they are correct but this is just by chance.

I'm not sure, if the data set, which was used for our results, included weather features, then the results are most likely invalid :(
And as far as I know they are... @MatthiasBaur did you run the latest test completely without weather features, so that they have not been in the .arff file?

**Comment by semioniy** [comment]
@goldbergtatyana till now we predicted the wrong stuff)

**Comment by goldbergtatyana** [comment]
thats super strange to me, because on the new data set @MatthiasBaur got just the same result as on this one.

**Comment by semioniy** [comment]
if we assume that with our previous dataset (with wrong classes) our prediction was comparable to random, then our current prediction is not much better.

**Comment by goldbergtatyana** [comment]
can you give me numbers for random @semioniy ?

**Comment by semioniy** [comment]
I don't have any numbers. Just thought, if till now we predicted wrong classes, it is the same as random.

**Comment by goldbergtatyana** [comment]
ok, one way to check for the random performance is to write a small program that will randomly assign one of 151 classes to 10.000 instances of @MatthiasBaur . Then the overall accuracy would be (number_of_correct_predictions)/10.000.

Another way is to calculate the random performance mathematically and it goes as following:
((1/151 \* frequency_of_pokemon1)+(1/51 \* frequency_of_pokemon2)+...+(1/151 \* frequency_of_pokemoon_151)) / 10.000

we assume that the predictor assigns one of 151 classes with the same probability, therefore each class gets 1/151 probability for being predicted. frequency_of_pokemon1 is the number of data points of pokemon1 in @MatthiasBaur 10K data set.

So, what is the random performance?

**Comment by goldbergtatyana** [comment]
Guys, please update the file and upload a new version of it on Kaggle ASAP ☝️

**Comment by semioniy** [comment]
@goldbergtatyana I still gather weather for it, as we had it in the first dataset. It takes time.

**Comment by goldbergtatyana** [comment]
I thought that the mistake happened when the data sets were merged (weather and the remaining set)? If this is the case, then there is no need in recalculating the weather features again.

**Comment by semioniy** [comment]
The mistake happened because of the bug. The bug is resolved now, so I just need to re-gather the dataset.

**Comment by semioniy** [comment]
A new version is there, ready for testing.

**Comment by goldbergtatyana** [comment]
Yep, the classes and pokemons Ids match now, thank you @semioniy. Another unexpected observation I made is that for most of sightings the the co-occurences with other pokemons are different between version2 and version3.

Can you explain where does this difference come from?

**Comment by bensLine** [comment]
@goldbergtatyana the co-occurrences calculation was also affected by the same bug. Thanks for pointing it out!

**Comment by sacdallago** [comment]
New statistics? 🏄

**Comment by semioniy** [comment]
My best result till now (with both 10k and 300k) was 21,8% right predicted pokemon, with only 8 features.

**Comment by goldbergtatyana** [comment]
That is great @semioniy! You need to telll us what you did, what were features and what us random?

**Comment by semioniy** [comment]
I took the 10k dataset after the bug was corrected, classified with bayesnet while deleting features, and ended up with Voting (BayesNet+IBK) with `closeToWater, city, urban, cooc13, cooc16, cooc19, cooc129` and got 21,8% correct predictions. Got same result afterwards with 300k, so 10k is enough. 
As I wrote already about random, it's pure my perception, I did no math. Just with _Bauchgefühl_ I thing real random will have 6-7%. Just thought that if we predict wrong thing, it's the same as not predicting and just picking one by chance.

**Comment by goldbergtatyana** [comment]
> I took the 10k dataset after the bug was corrected, classified with bayesnet while deleting features, and ended up with Voting (BayesNet+IBK) with closeToWater, city, urban, cooc13, cooc16, cooc19, cooc129 and got 21,8% correct predictions. Got same result afterwards with 300k, so 10k is enough. 

Cool!

> As I wrote already about random, it's pure my perception, I did no math. Just with Bauchgefühl I thing real random will have 6-7%. 

That's cute to read but the approach of _Bauchgefühl_ is not scientific at all 😈 at all 😈 at all 😈 !!!
A naive random would be to divide 100% by 151 classes, but this calculation asumes that each class is repesented by an equal number of pokemons. 
A correct way to calculate random is described a few comments above. 

So, what is random?

**Comment by semioniy** [comment]
> ((1/151 \* frequency_of_pokemon1)+(1/151 \* frequency_of_pokemon2)+...+(1/151 \* frequency_of_pokemoon_151)) / 10.000

= 1/151 x (frequency_of_pokemon1+frequency_of_pokemon2...+frequency_of_pokemon151)/1000;
sum of frequencies = 1, so it is 1/151x1/1000

I'll think of how to figure this number out, but why do we need it in the first place?

**Comment by goldbergtatyana** [comment]
> I'll think of how to figure this number out

It is simpler than you think. All you need to do is to count the number of pokemon 1 in our 10K dataset, of pokemon 2 and so on

>  why do we need it in the first place?

how else do we know that we are not random?

**Comment by semioniy** [comment]
Well, after couple of hours of attempts I can conclude:
If this is right: 
`numOfRightPredicted = SUM((1/numOfClasses)*numOfInstancesInEachClass/numOfAllInstances)`, then in both cases (even und uneven distribution) number of right predicted instances is equal to 1/numOfClasses. In that case our random would be 1/151=0,71%, or even less. We have 21-22%, so it seems to be not random. Still have no idea, how could we get 21% with wrong classes.

**Comment by goldbergtatyana** [comment]
Which reminds me @semioniy of the kaggle thing again 😼 

I highlighted a few issues and left comments to them in the google doc that I see are missing on the kaggle site. Please add those to the description of our data set: https://docs.google.com/document/d/1dIKvxOshOCnu2by5gIQR3rceUAs_4cfhg3TDxS9bPnM/edit

And one more of 'something is missing': what happened to our awesome 2G sightings data set? Is there help needed for splitting it? Let us know.

**Comment by goldbergtatyana** [comment]
@semioniy: NOW we need the 2G dataset on Kaglle, this really cannot wait anymore.

Too many people are looking at the data and one of our jewels is not up yet 😿What problems are you running into with uploading the set?

**Comment by semioniy** [comment]
It is already there, in discussion Datadump.

**Comment by goldbergtatyana** [comment]
Oh ok, I'm only on mobile since yesterday, so couldn't see it being on kaggle myself yet. Thanks for putting it up and thanks for working on a more comprehensive description for the first file, @semioniy !

**Comment by semioniy** [comment]
Descriptions on Kaggle have been updated.

**Comment by sacdallago** [comment]
I think we can close this for now
