### ISSUE TITLE
Generate arff file from dummy data

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#4]

**Comment by bensLine** [comment]
@marwage I added you as assignee since your implementation is more advanced than mine.
However, for the arff file I'd suggest to use the Pokemon id as class label and to combine all dummy.json files into one arff file, so that we have a bigger data set to train the classifier with. (I know in JS we can combine them but for Weka one file is be better)

**Comment by goldbergtatyana** [comment]
waiting to see the arff file 😉

**Comment by bensLine** [comment]
Hey @goldbergtatyana, I posted an arff already several days ago https://github.com/PokemonGoers/PredictPokemon-2/blob/feature/test_data/test_data/pokeDummyData.arff see [comment](https://github.com/PokemonGoers/PredictPokemon-2/issues/2#issuecomment-242033789)

Anyway, we'll add one to develop during this day.
