### ISSUE TITLE
Create API

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#44]
Create a API which team E will use to get predictions for a given location and timestamp.
- input: lat/lon + timestamp 
- then predict for radius of 5 km in every cell id (90m):
  `predicted pokemonId, prediction accuracy, lat/lon (cell id center)`

return results as list

**Comment by sacdallago** [comment]
I would suggest the programmatical API, not the REST API.
Aka: just provide a way for people to import your package `var P = require('predictions..');`  and then call something like `P.predict(lat,lng,timestamp)`

**Comment by gyachdav** [comment]
Additional params should be:
- weather: since we're having issues querying weather services multiple times, we can just let clients donthebworknfor us 
- same for terrain: spread the lookup load across clients. 

What other params can we offload to the clients?

**Comment by sacdallago** [comment]
@gyachdav but this should be optional params, right? Theoretically it's trough a call of `.predict(..)` that these features get added to the data-point to then generate a prediction. Outsourcing this to the caller is shifting the computation to a different place, but at the end of the day it's always gonna be the same process/machine that runs the computation (though, sure: if in the future someone finds a faster API for weather that returns the same params as the one used for the predictions, then they can plug this info in)

**Comment by goldbergtatyana** [comment]
We found the weather feature not to be relevant for the predictions. Thanks a lot @semioniy for so tirelesly working on the data for this particular feature. @MatthiasBaur will provide an overview in [issue 62](https://github.com/PokemonGoers/PredictPokemon-2/issues/62) of features that will be used in the end.
