### ISSUE TITLE
Classifier performance on the 50K data set

### ISSUE THREAD

**Issue by goldbergtatyana** [PokemonGoers/PredictPokemon-2#47]
What is your feature set, classifier and the performance on the 50K data set?

**Comment by goldbergtatyana** [comment]
@MatthiasBaur status?

**Comment by MatthiasBaur** [comment]
Status inc tonight.

**Comment by sacdallago** [comment]
😴 zombie issue

**Comment by bensLine** [comment]
true, running only attribute selection on the 50k file with 208 features in total takes already forever -_-  feature set looks like this (there are 151 co-occurance features):
- pokemonId numeric
- latitude numeric
- longitude numeric
- appearedLocalTime string
- _id string
- cellId_90m numeric
- cellId_180m numeric
- cellId_370m numeric
- cellId_730m numeric
- cellId_1460m numeric
- cellId_2920m numeric
- cellId_5850m numeric
- appearedTimeOfDay {night, evening, afternoon, morning}
- appearedHour numeric
- appearedMinute numeric
- appearedDayOfWeek {dummy_day, Sunday, Saturday}
- appearedDay numeric
- appearedMonth numeric
- appearedYear numeric
- terrainType numeric
- closeToWater {false, true}
- city {Mexico_City, New_York, Los_Angeles, Perth,....}
- continent {America, Australia, Europe, Asia, America/Indiana, Pacific, America/Argentina, Africa}
- weather {Foggy, Clear, PartlyCloudy, MostlyCloudy, Overcast, Rain, .....}
- temperature numeric
- windSpeed numeric
- windBearing numeric
- pressure numeric
- weatherIcon {fog, clear-night, partly-cloudy-night, partly-cloudy-day, cloudy, clear-day, rain, wind}
- sunriseMinutesMidnight numeric
- sunriseHour numeric
- sunriseMinute numeric
- sunriseMinutesSince numeric
- sunsetMinutesMidnight numeric
- sunsetHour numeric
- sunsetMinute numeric
- sunsetMinutesBefore numeric
- population_density numeric
- urban {true, false}
- suburban {true, false}
- midurban {true, false}
- rural {false, true}
- gymDistanceKm numeric
- gymIn100m {true, false}
- gymIn250m {true, false}
- gymIn500m {true, false}
- gymIn1000m {true, false}
- gymIn2500m {true, false}
- gymIn5000m {true, false}
- pokestopDistanceKm numeric
- pokestopIn100m {true, false}
- pokestopIn250m {true, false}
- pokestopIn500m {true, false}
- pokestopIn1000m {true, false}
- pokestopIn2500m {true, false}
- pokestopIn5000m {true, false}
- co-occurance_1 ... 151 {false, true}

Results about the performance will follow with more details

**Comment by goldbergtatyana** [comment]
hm, feature selection is usually a really quick matter. it would be much helpful debugging your issues if you would provide your input file and the parameters you use for the tools.

**Comment by MatthiasBaur** [comment]
Performance was tested mainly on the 10k set. I will reference the results shortly.

**Comment by MatthiasBaur** [comment]
#62
