### ISSUE TITLE
Use S2 library to create cell id features from lat/lon

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#5]
- S2 JS library: https://github.com/Daplie/s2-geometry.js
- nice blog post about S2 library: http://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/

**Comment by bensLine** [comment]
I tested the library and **approximated** the cell distances for the different levels. I'll add the code when https://github.com/PokemonGoers/PredictPokemon-2/issues/4 is merged, as it is only a simple script now..
- level 0, avg distance: 10007.543398km 10007543.398m
- level 1, avg distance: 6227.188138km  6227188.138m
- level 2, avg distance: 3219.191285km  3219191.285m
- level 3, avg distance: 1501.842929km  1501842.929m
- level 4, avg distance: 724.902798km   724902.798m
- level 5, avg distance: 371.812270km   371812.270m
- level 6, avg distance: 188.665493km   188665.493m
- level 7, avg distance: 94.034835km    94034.835m
- level 8, avg distance: 46.852384km    46852.384m
- level 9, avg distance: 23.406853km    23406.853m
- level 10, avg distance: 11.698556km   11698.556m
- level 11, avg distance: 5.851886km    5851.886m
- level 12, avg distance: 2.925292km    2925.292m
- level 13, avg distance: 1.462483km    1462.483m
- level 14, avg distance: 0.731261km    731.261m
- level 15, avg distance: 0.365620km    365.620m
- level 16, avg distance: 0.182811km    182.811m
- level 17, avg distance: 0.091405km    91.405m
- level 18, avg distance: 0.045702km    45.702m
- level 19, avg distance: 0.022851km    22.851m
- level 20, avg distance: 0.011426km    11.426m
- level 21, avg distance: 0.005713km    5.713m
- level 22, avg distance: 0.002856km    2.856m
- level 23, avg distance: 0.001428km    1.428m
- level 24, avg distance: 0.000714km    0.714m
- level 25, avg distance: 0.000357km    0.357m
- level 26, avg distance: 0.000179km    0.179m
- level 27, avg distance: 0.000089km    0.089m
- level 28, avg distance: 0.000045km    0.045m
- level 29, avg distance: 0.000022km    0.022m
- level 30, avg distance: 0.000011km    0.011m

**Comment by goldbergtatyana** [comment]
Nice job @bensLine! Does the library allow to exclude regions such as seas, oceans and Antarctica? Would be nice to work with only those points that are really reachable by users.

**Comment by bensLine** [comment]
relates to #25. S2 cell id features have been implemented as example feature source. the script to print the average distance is also included.

**Comment by bensLine** [comment]
@goldbergtatyana, unfortunately, we do not get any further information from the S2 library, it only provides the cell id. if we extract terrain features #7 we can infer this information.
