### ISSUE TITLE
another data dump from reddit

### ISSUE THREAD

**Issue by jonas-he** [PokemonGoers/PredictPokemon-2#64]
Dont know if you can make use iof it, was just browsing reddit and found this:

https://www.reddit.com/r/pokemongodev/comments/56r4f3/go_scan_heres_the_data_we_collected_over_the_last/

https://www.reddit.com/r/pokemongodev/comments/56p3ht/data_dump_my_archive_of_15m_points_from_migration/

https://www.reddit.com/r/pokemongodev/comments/56i1x1/github_json_a_way_to_share_public_data_dumps_and/

**Comment by bensLine** [comment]
thanks, for the info!
