### ISSUE TITLE
URGENT: Integration with PokeData

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PredictPokemon-2#67]
This issue is a status update request and an urgent call to complete the integration with project A so we can move ahead with the launch. 

Please make here a task list and tick completed steps so we will know what is needed in order to complete this integration. 

@semioniy @bensLine @MatthiasBaur @Aurel-Roci

**Comment by Aurel-Roci** [comment]
Since we are going to provide a npm package for the predictions, what is needed from team A is adding java in the docker container, since we are using java to run the weka file for the predictions.
- [x] **Add Java to the Docker Container**
- [x] **Add the prediction package in the dependencies**

**Comment by jonas-he** [comment]
Java is done. Apart from that only adding a dependency is not gonna cut it right? we'll need to add a new API route, which then listens on prediction requests and calls something like a `predict(lat, lng, timestamp)` function from your package. However i didnt find such in the description here https://www.npmjs.com/package/predict-pokemon

**Comment by Aurel-Roci** [comment]
Thanks for letting me know, I will add that to the description. You can find it here the way it works. https://github.com/PokemonGoers/PokeData/issues/183

**Comment by bensLine** [comment]
@jonas-he fyi, we have to adapt the URL when the 6GB database is available. Besides, you need to unzip the `json/pokestop_groups.7z` file in the prediction npm package in order to use it. And it takes a while to initialize the module.

**Comment by gyachdav** [comment]
It has been 13 days since this issue was open with the label URGENT and the last response here is 10 days old... We need an answer here about status ASAP! aka As Soon As Possible! 😡 

@PokemonGoers/pokedata

**Comment by Aurel-Roci** [comment]
@gyachdav The only reason this issue is kept open, is so that if team A has any further questions on the predictions the can ask here. The integration is done.

**Comment by gyachdav** [comment]
This is not how it should be handled. If this is done then the issue is closed. If project A has some questions they are welcome to open a new issue label it "questions" and reference this issue if needed. 

Now, if this is done - is there a demo where we can see the integration actually working?
