### ISSUE TITLE
Add terrain features

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#7]
Add features to describe the terrain by using the existing location feature. Possible features used in a [tutorial](http://tutorials.pluralsight.com/big-data/use-a-data-analytics-tool-to-predict-where-the-pokemon-are-going-to-appear) are the proximity to:
- Water
- Grass
- Buildings

**Comment by bensLine** [comment]
Those features might be provided by group A, follow the discussion at https://github.com/PokemonGoers/PokeData/issues/71

**Comment by sacdallago** [comment]
Some data you might need to generate yourself.
PokeData should be about Pokémon data, not terrain features of the actual world :) it would be also unfair to ask the people on group A to produce this data which is irrelevant for their task ;)

It also introduces you to an important concept in data mining: you need to make feature engineering to discover new data which might be interesting to build a better model, but which is not directly part of the initial test data.
This is **not** to restrain from asking project A to implement new data sources, but please separate between things that are relevant to your project and things that are relevant to everyone/the concept of a Pokémon-centric API

**Comment by bensLine** [comment]
Yes, of course! It was not meant as a request, we just want to avoid implementing features twice :)

**Comment by bensLine** [comment]
might be of interest: http://pokemongohub.net/pokemon-go-spawn-points-modeled-open-street-map-data/

**Comment by jonas-he** [comment]
@bensLine feature is implemented from our side, sorry for the long wait (see https://github.com/PokemonGoers/PokeData/issues/130)

**Comment by MatthiasBaur** [comment]
Looks nice, thank you!

**Comment by bensLine** [comment]
PokemonGoers/PokeData#130 was adapted and added in #36 and #37
