### ISSUE TITLE
Ignore sightings without pokemonId

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PredictPokemon-2#77]
Requested in #76

**Comment by jonas-he** [comment]
@bensLine retested your fix and it does not solve the problem. It's because `elem['pokemonId']` evaluates to `undefined` and as a result `elem['pokemonId'] !== null` evaluates to `true`  (in the case of a non existing pokemonId)

**Comment by Aurel-Roci** [comment]
@jonas-he added a check for undefined id. Should be fine now

**Comment by bensLine** [comment]
sorry about that! thanks Aurel
