### ISSUE TITLE
Convert UTC to Local Time Zone

### ISSUE THREAD

**Issue by MatthiasBaur** [PokemonGoers/PredictPokemon-2#8]
The API data comes in the UTC format. For the learning process it has to be converted to local time using the timestamp and the coordinates.

**Comment by MatthiasBaur** [comment]
This issue could be closed, but I suggest leaving it open until we get feedback from the data team.

**Comment by jonas-he** [comment]
@MatthiasBaur already implemented, see https://github.com/PokemonGoers/PokeData/issues/130

**Comment by MatthiasBaur** [comment]
See https://github.com/PokemonGoers/PokeData/issues/130
